### pysus

In [ ]:
!pip install PySUS

### import

In [ ]:
import pandas as pd
from pysus.utilities.readdbc import read_dbc

### download SIHSUS

In [16]:
RDES1801 = 'RDES1801.dbc'
SIHES1801 = read_dbc(RDES1801, encoding='iso-8859-1')
SIHES1801.head()

    UF_ZI ANO_CMPT MES_CMPT ESPEC  ... TPDISEC6 TPDISEC7 TPDISEC8 TPDISEC9
0  320000     2018       01    03  ...        0        0        0        0
1  320000     2018       01    01  ...        0        0        0        0
2  320000     2018       01    01  ...        0        0        0        0
3  320000     2018       01    01  ...        0        0        0        0
4  320000     2018       01    01  ...        0        0        0        0

[5 rows x 113 columns]

In [ ]:
SIHES.to_csv('SIHES2018.csv')